export const FETCH_DISH_REQUEST = 'FETCH_DISH_REQUEST';
export const FETCH_DISH_SUCCESS = 'FETCH_DISH_SUCCESS';
export const FETCH_DISH_FAILURE = 'FETCH_DISH_FAILURE';

export const UPDATE_DISH_REQUEST = 'UPDATE_DISH_REQUEST';
export const UPDATE_DISH_SUCCESS = 'UPDATE_DISH_SUCCESS';
export const UPDATE_DISH_FAILURE = 'UPDATE_DISH_FAILURE';

export const ADD_DISH_REQUEST = 'ADD_DISH_REQUEST';
export const ADD_DISH_SUCCESS = 'ADD_DISH_SUCCESS';
export const ADD_DISH_FAILURE = 'ADD_DISH_FAILURE';

export const FETCH_DISHES_REQUEST = 'FETCH_DISHES_REQUEST';
export const FETCH_DISHES_SUCCESS = 'FETCH_DISHES_SUCCESS';
export const FETCH_DISHES_FAILURE = 'FETCH_DISHES_FAILURE';

export const FETCH_ORDERS_REQUEST = 'FETCH_ORDERS_REQUEST';
export const FETCH_ORDERS_SUCCESS = 'FETCH_ORDERS_SUCCESS';
export const FETCH_ORDERS_FAILURE = 'FETCH_ORDERS_FAILURE';